export const TRANSLATIONS = {
  en: {
    appName: "Lupra AI Studio",
    tagline: "Ultra-realistic image generation powered by advanced AI.",
    newGeneration: "New Generation",
    history: "History",
    proPlan: "Pro Plan",
    freePlan: "Free Plan",
    upgradeToPro: "Upgrade to Pro",
    premiumActive: "Premium Active",
    readyToCreate: "Ready to create?",
    describe: "Describe what you want to see and Lupra AI will generate an ultra-realistic masterpiece.",
    inputPlaceholder: "A futuristic cybernetic tiger in a neon alleyway...",
    turboMode: "Turbo Mode",
    liteMode: "Lite Mode",
    adminPanel: "Lupra Admin Panel",
    exitAdmin: "Exit Admin",
    totalThreads: "Total Threads",
    queueLoad: "Queue Load",
    apiStatus: "API Status",
    activeUsers: "Active Users"
  },
  ur: {
    appName: "لوپرا AI اسٹوڈیو",
    tagline: "جدید AI کے ذریعے حقیقت پسندانہ تصاویر کی تخلیق۔",
    newGeneration: "نئی تخلیق",
    history: "تاریخ",
    proPlan: "پرو پلان",
    freePlan: "فری پلان",
    upgradeToPro: "پرو میں اپ گریڈ کریں",
    premiumActive: "پریمیم فعال",
    readyToCreate: "تخلیق کے لیے تیار؟",
    describe: "بیان کریں کہ آپ کیا دیکھنا چاہتے ہیں اور لوپرا AI ایک شاہکار تخلیق کرے گا۔",
    inputPlaceholder: "نیون گلی میں ایک مستقبل کا شیر...",
    turboMode: "ٹربو موڈ",
    liteMode: "لائٹ موڈ",
    adminPanel: "لوپرا ایڈمن پینل",
    exitAdmin: "ایڈمن سے باہر نکلیں",
    totalThreads: "کل تھریڈز",
    queueLoad: "قطار کا بوجھ",
    apiStatus: "API کی صورتحال",
    activeUsers: "فعال صارفین"
  },
  hi: {
    appName: "लुप्रा AI स्टूडियो",
    tagline: "उन्नत AI द्वारा संचालित अति-यथार्थवादी छवि निर्माण।",
    newGeneration: "नया निर्माण",
    history: "इतिहास",
    proPlan: "प्रो प्लान",
    freePlan: "फ्री प्लान",
    upgradeToPro: "प्रो में अपग्रेड करें",
    premiumActive: "प्रीमियम सक्रिय",
    readyToCreate: "निर्माण के लिए तैयार?",
    describe: "बताएं कि आप क्या देखना चाहते हैं और लुप्रा AI एक उत्कृष्ट कृति बनाएगा।",
    inputPlaceholder: "नियॉन गली में एक भविष्यवादी बाघ...",
    turboMode: "टर्बो मोड",
    liteMode: "लाइट मोड",
    adminPanel: "लुप्रा एडमिन पैनल",
    exitAdmin: "एडमिन से बाहर निकलें",
    totalThreads: "कुल थ्रेड्स",
    queueLoad: "कतार भार",
    apiStatus: "API स्थिति",
    activeUsers: "सक्रिय उपयोगकर्ता"
  }
};
